const BASE_ACTION = 'ALARMS_LIST/';
export const FETCH_ALARMS_START = `${BASE_ACTION}FETCH_ALARMS_START`;
export const FETCH_ALARMS_SUCCESS = `${BASE_ACTION}FETCH_ALARMS_SUCCESS`;
export const FETCH_ALARMS_FAIL = `${BASE_ACTION}FETCH_ALARMS_FAIL`;
export const SET_EMAIL_NOTIFICATION_START = `${BASE_ACTION}SET_EMAIL_NOTIFICATION_START`;
export const SET_EMAIL_NOTIFICATION_SUCCESS = `${BASE_ACTION}SET_EMAIL_NOTIFICATION_SUCCESS`;
export const SET_EMAIL_NOTIFICATION_FAIL = `${BASE_ACTION}SET_EMAIL_NOTIFICATION_FAIL`;
