const BASE_ACTION = 'CHARTS/';
export const TIME_SERIES_CHANGE_SUCCESS = `${BASE_ACTION}TIME_SERIES_CHANGE_SUCCESS`;
export const TIME_SERIES_ADD_SUCCESS = `${BASE_ACTION}TIME_SERIES_ADD_SUCCESS`;
export const TIME_SERIES_DELETE_SUCCESS = `${BASE_ACTION}TIME_SERIES_DELETE_SUCCESS`;
export const CHARTS_POST_START = `${BASE_ACTION}CHARTS_POST_START`;
export const CHARTS_POST_FAIL = `${BASE_ACTION}CHARTS_POST_FAIL`;