const BASE_ACTION = 'DASHBOARD/';
export const FETCH_DASHBOARD_START = `${BASE_ACTION}FETCH_DASHBOARD_START`;
export const FETCH_DASHBOARD_SUCCESS = `${BASE_ACTION}FETCH_DASHBOARD_SUCCESS`;
export const FETCH_DASHBOARD_FAIL = `${BASE_ACTION}FETCH_DASHBOARD_FAIL`;
export const TIME_SERIES_CHANGE_START = `${BASE_ACTION}TIME_SERIES_CHANGE_START`;
export const TIME_SERIES_CHANGE_SUCCESS = `${BASE_ACTION}TIME_SERIES_CHANGE_SUCCESS`;
export const TIME_SERIES_CHANGE_FAIL = `${BASE_ACTION}TIME_SERIES_CHANGE_FAIL`;

