const BASE_ACTION = 'DASHBOARD/';
export const FETCH_DASHBOARD_START = `${BASE_ACTION}FETCH_DASHBOARD_START`;
export const FETCH_DASHBOARD_SUCCESS = `${BASE_ACTION}FETCH_DASHBOARD_SUCCESS`;
export const FETCH_DASHBOARD_FAIL = `${BASE_ACTION}FETCH_DASHBOARD_FAIL`;
export const TIME_SERIES_CHANGE_START = `${BASE_ACTION}TIME_SERIES_CHANGE_START`;
export const TIME_SERIES_CHANGE_SUCCESS = `${BASE_ACTION}TIME_SERIES_CHANGE_SUCCESS`;
export const TIME_SERIES_CHANGE_FAIL = `${BASE_ACTION}TIME_SERIES_CHANGE_FAIL`;
export const GAUGE_CHANGE_START = `${BASE_ACTION}GAUGE_CHANGE_START`;
export const GAUGE_CHANGE_SUCCESS = `${BASE_ACTION}GAUGE_CHANGE_SUCCESS`;
export const GAUGE_CHANGE_FAIL = `${BASE_ACTION}GAUGE_CHANGE_FAIL`;
export const TAG_CHANGE_START = `${BASE_ACTION}TAG_CHANGE_START`;
export const TAG_CHANGE_SUCCESS = `${BASE_ACTION}TAG_CHANGE_SUCCESS`;
export const TAG_CHANGE_FAIL = `${BASE_ACTION}TAG_CHANGE_FAIL`;
export const TRIGGER_CHANGE_START = `${BASE_ACTION}TRIGGER_CHANGE_START`;
export const TRIGGER_CHANGE_SUCCESS = `${BASE_ACTION}TRIGGER_CHANGE_SUCCESS`;
export const TRIGGER_CHANGE_FAIL = `${BASE_ACTION}TRIGGER_CHANGE_FAIL`;

