const BASE_ACTION = 'DASHBOARD/';
export const FETCH_DASHBOARD_START = `${BASE_ACTION}FETCH_DASHBOARD_START`;
export const FETCH_DASHBOARD_SUCCESS = `${BASE_ACTION}FETCH_DASHBOARD_SUCCESS`;
export const FETCH_DASHBOARD_FAIL = `${BASE_ACTION}FETCH_DASHBOARD_FAIL`;
