const BASE_ACTION = 'HEADER/';
export const SET_ADMIN_STATUS = `${BASE_ACTION}SET_ADMIN_STATUS`;
export const SET_SYSTEM_NAME = `${BASE_ACTION}SYSTEM_NAME`;
export const FETCH_SYSTEM_NAME_START = `${BASE_ACTION}FETCH_SYSTEM_NAME_START`;
export const FETCH_SYSTEM_NAME_SUCCESS = `${BASE_ACTION}FETCH_SYSTEM_NAME_SUCCESS`;
export const FETCH_SYSTEM_NAME_FAIL = `${BASE_ACTION}FETCH_SYSTEM_NAME_FAIL`;