const BASE_ACTION = 'POLLING/';
export const FETCH_POLLING_SUCCESS = `${BASE_ACTION}FETCH_POLLING_SUCCESS`;
export const FETCH_POLLING_FAIL = `${BASE_ACTION}FETCH_POLLING_FAIL`;
export const FETCH_POLLING_START = `${BASE_ACTION}FETCH_POLLING_START`;
