const BASE_ACTION = 'SYSTEM_SELECT/'
export const FETCH_SYSTEMS_START = `${BASE_ACTION}FETCH_SYSTEMS_START`
export const FETCH_SYSTEMS_SUCCESS = `${BASE_ACTION}FETCH_SYSTEMS_SUCCESS`
export const FETCH_SYSTEMS_FAIL = `${BASE_ACTION}FETCH_SYSTEMS_FAIL`
export const UPON_SYSTEM_SELECTION = `${BASE_ACTION}UPON_SYSTEM_SELECTION`
