const BASE_ACTION = 'TAGS_LIST/';
export const FETCH_TAGS_START = `${BASE_ACTION}FETCH_TAGS_START`;
export const FETCH_TAGS_SUCCESS = `${BASE_ACTION}FETCH_TAGS_SUCCESS`;
export const FETCH_TAGS_FAIL = `${BASE_ACTION}FETCH_TAGS_FAIL`;
export const POST_TAG_START = `${BASE_ACTION}POST_TAG_START`;
export const POST_TAG_SUCCESS = `${BASE_ACTION}POST_TAG_SUCCESS`;
export const POST_TAG_FAIL = `${BASE_ACTION}POST_TAG_FAIL`;
