const BASE_ACTION = 'TAGS_LIST/';
export const FETCH_TAGS_START = `${BASE_ACTION}FETCH_TAGS_START`;
export const FETCH_TAGS_SUCCESS = `${BASE_ACTION}FETCH_TAGS_SUCCESS`;
export const FETCH_TAGS_FAIL = `${BASE_ACTION}FETCH_TAGS_FAIL`;
